name: Generate HTML and Create New Branch

on:
  push:
    paths:
      - '**/*.py'
      - '**/*.toml'

jobs:
  generate_html:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取倉庫代碼
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 安裝 Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      # 3. 將 Poetry 加入 PATH
      - name: Add Poetry to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      # 4. 安裝依賴
      - name: Install dependencies with Poetry
        run: poetry install

      # 5. 執行 convert.py 生成 index.html
      - name: Run convert.py to generate index.html
        run: poetry run python convert.py

      # 6. 建立新分支並提交更新的 index.html
      - name: Commit and push to new branch
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Generate new index.html"
          branch: generate-index-html  # 新分支名稱
          delete-branch: true
          title: "Auto-generated index.html"
          body: "This PR contains the updated index.html generated by convert.py."
          add-paths: index.html
